--USE THE BikeStores DATABASE
USE BikeStores
GO

--CREATE A VIEW CALEED thursday_view
CREATE VIEW thursday_view AS SELECT * FROM sales.stores

--VIEW QUANTITITES WITHING THE VIRTUAL TABLE/VIEW
SELECT * FROM thursday_view

--DISPLAY ALL CREATED VIEWS
SELECT TABLE_SCHEMA, TABLE_NAME  FROM INFORMATION_SCHEMA.VIEWS

--VIEW CONTENTS OF THE sales.order_items TABLE
SELECT * FROM sales.order_items

--CREATE | ALTER VIEW CALLED sales_view
CREATE OR ALTER VIEW sales_view 
AS 
SELECT TOP 100
	* 
FROM 
	sales.order_items
WHERE list_price>=1000

--VIEW CONTENTS OF THE VIRTUAL TABLE
SELECT * FROM sales_view

--DELETE ROW WHERE item_id=2 FROM THE VIEW sales_view
DELETE FROM sales_view
WHERE item_id=2

--UPDATE VIEW CONTENT
UPDATE sales_view SET list_price=2000.00 WHERE order_id=1

--DISPLAY ALL CREATED VIEWS
SELECT TABLE_SCHEMA, TABLE_NAME  FROM INFORMATION_SCHEMA.VIEWS

--DELETE VIEW
DROP VIEW thursday_view

--RENAME EXISTING VIEW
EXEC sp_rename thursday_view, new_view_name



